### ISSUE TITLE
cancel or pause Action gives undefined exception

### ISSUE THREAD

**Issue by philippjenni** [kukhariev/ngx-uploadx#10]
If you call a cancel, cancelAll, pause oder pauseAll Action and the queue item where the action is applied is not in uploading state, there is an error "abort is not function".

The problem is in the "uploader.ts" line: 45. It's look like the the problem is created in line 71. The new object has no abort() function in the state object.

Version 2.2.0
Browser: Chrome

**Comment by kukhariev** [comment]
Hi,
please test new version.

**Comment by philippjenni** [comment]
Problem is not complete fixed. If you press pauseAll more than one times, the exceptions raised after the second call.

**Comment by philippjenni** [comment]
Follow test cases to reproduce the problem.

- Select File - Upload - Pause - Pause -> Exception (Abort not a function)
- Select File - Upload - Wait if Complete - Pause -> Exception (Cannot set property 'status' of undefined)
