### ISSUE TITLE
Canceled Files cannot be selected again

### ISSUE THREAD

**Issue by philippjenni** [kukhariev/ngx-uploadx#13]
You can't select a file again, which upload is canceled.

Follow Tasks to reproduce: 

- Select File -> Upload -> Cancel All (During Upload) -> Select same File again (File not in List)

**Comment by kukhariev** [comment]
I added  [reset FileList workaround:](https://github.com/kukhariev/ngx-uploadx/blob/c0cb66ff2a86e1e55c04265fa080fa1eaa27149a/src/app/directive-way/directive-way.component.html#L6)
```html
        <input
          #files
          (click)="files.value = ''"
          type="file"
          [uploadx]="options"
...
```

**Comment by philippjenni** [comment]
With the workaround the problem is gone ...
