### ISSUE TITLE
'uploadAll' control should not stop the current uploading files

### ISSUE THREAD

**Issue by wil92** [kukhariev/ngx-uploadx#16]
I think is better only put as queue the uploads than are in pause (not the uploading ones) and then call the processQueue()

PD: I can do it, but I'am asking for see what was the initial idea with that action

**Comment by kukhariev** [comment]
if you mean this code:
```ts
      case 'upload':
        const uploadId = event.uploadId || event.itemOptions.uploadId;
        const upload = this.queue.find(f => f.uploadId === uploadId);
        if (this.concurrency - this.runningProcess() > 0) {
          upload.upload(event.itemOptions);
        } else if (upload.status === ('added' as UploadStatus)) {
          upload.status = 'queue' as UploadStatus;
        }
        break;
```
it looks broken.

**Comment by wil92** [comment]
I code that, what i did there was a condition before start upload, because the file should not start upload if the concurrency is full, and put as queue if the file is as added for start the upload after the concurrency is free.

I talking about this part
```
case 'uploadAll':
        this.queue.filter(f => f.status !== 'uploading').forEach(f => (f.status = 'queue'));
        this.processQueue();
        break;
```

why stop the current uploading files and then call the processQueue?, is not the same call only the processQueue method

**Comment by wil92** [comment]
I think should be like this

```ts
case 'uploadAll':
        this.queue.filter(f => f.status !== 'paused').forEach(f => (f.status = 'queue'));
        this.processQueue();
        break;
```

**Comment by kukhariev** [comment]
`case 'uploadAll':`
but how quick `unpause` all paused?

`case 'upload':`
try   upload  5  files  on http://localhost:4200/service-way

**Comment by wil92** [comment]
sorry in the uploadAll i didn't see the `!==`, my foul. That why i didn't change anything there.

I test that, I upload 5 files at the same time and was working, with the restriction that only 2 file at the same time are coping and after one of the uploading finish then start the first in queue to upload. What is the error you find there?

I'm going to close this issue an create a new one for the upload action
