### ISSUE TITLE
ngx-uploadx chunk file send RequestHeader Content-Range: bytes */xxxx

### ISSUE THREAD

**Issue by narutomxc** [kukhariev/ngx-uploadx#179]
options setting
`options: UploadxOptions = {
    endpoint: API_URL,
    token: () => this.authService.token,
    chunkSize: 1024 * 1024 * 1,
    autoUpload: false
  };`

I want to send a request header with:
- Content-Range: bytes 0-1000/3000

But right now request header with:
- Content-Range: bytes */3000

Version
- Used `ngx-uploadx 3.3.4`
- Used `Angular 8.2.14`

Refference: [https://github.com/senolatac/chunk-upload/tree/develop](url)

**Comment by kukhariev** [comment]
[ server must respond with code 201 to the post request](https://github.com/kukhariev/node-uploadx/blob/master/proto.md). 

https://github.com/senolatac/chunk-upload/blob/f6567d2fef27b1199c5d4ddd823d58a52e48a331/file-uploader-server/src/main/java/com/sha/fileuploader/controller/FileUploaderController.java#L103

Probably should:
```java 
ServletUtil.createLocation("ngx-upload/"+metadata.getUniqueId()), HttpStatus.CREATED);
```

**Comment by narutomxc** [comment]
When i change HttpStatus to CREATED

i can post Upload file

but not put file

image: [https://s3-ap-southeast-1.amazonaws.com/img-in-th/49ef3549f41be39385a1d65af829d4de.png](url)

**Comment by narutomxc** [comment]
REQUESTS OVERVIEW

- `create:`

```
POST http://localhost:8000/upload-file
Content-Type: application/json; charset=UTF-8
X-Upload-Content-Length: 13057291
X-Upload-Content-Type: video/mp4

{"name":"file.MP4","mimeType":"video/mp4","size":13057291,"lastModified":1547276404709,"uploadId":"8d03d7e3"}
```

```
HTTP/1.1 201 Created
Location: upload-file/f38b082c-dbc6-4f8c-bb47-e9acb1a5338a
Content-Length: 0
```
- `send chunk: 1`

```
PUT http://localhost:8000/upload-file/f38b082c-dbc6-4f8c-bb47-e9acb1a5338a
Content-Type: application/octet-stream
Content-Range: bytes 0-2097151/13057291
Content-Length: 2097152

[BYTES 0-2097151]
```

```
HTTP/1.1 308 Resume Incomplete
Range: bytes=0-2097151
Content-Length: 0
```

- `send chunk: 2`

```
PUT http://localhost:8000/upload-file/f38b082c-dbc6-4f8c-bb47-e9acb1a5338a
Content-Type: application/octet-stream
Content-Range: bytes 2097152-4194303/13057291
Content-Length: 2097152

[BYTES 2097152-4194303]
```

```
HTTP/1.1 308 Resume Incomplete
Range: bytes=2097152-4194303
Content-Length: 0
```

But !!!

- `send chunk: 3`

```
PUT http://localhost:8000/upload-file/f38b082c-dbc6-4f8c-bb47-e9acb1a5338a
Content-Type: application/octet-stream
**Content-Range: bytes 0-2097151/13057291**
Content-Length: 2097152

[BYTES 0-2097151]
```

```
HTTP/1.1 308 Resume Incomplete
**Range: bytes=0-2097151**
Content-Length: 0
```

**Comment by narutomxc** [comment]
I'm stamp log in database

image : https://s3-ap-southeast-1.amazonaws.com/img-in-th/d8cd5034a7f1bff27b7766626d6661a5.png

**Comment by kukhariev** [comment]
send chunk: 2
...
HTTP/1.1 308 Resume Incomplete
Range: bytes=_2097152-4194303_ - **error here,  should be Range: bytes=0-4194303**
Content-Length: 0

**Comment by narutomxc** [comment]
Some file upload error because  send `Content-Range: bytes */3000`, 

How do I clear the cache of files that I uploaded?

**Comment by kukhariev** [comment]
LocalStorage ->  UPLOADX-V3.0-xxx  key.

I'll do a less restrictive range check.

**Comment by narutomxc** [comment]
I would like a sample (back-end java spring-boot) about file integration. When all uploads are complete,

in code filer.component.ts line 104-115,

Do I need to create an hash? (gen hash, send hash to back-end)

Reference: https://github.com/senolatac/chunk-upload/blob/develop/file-uploader-client/src/app/filer/filer.component.ts

**Or if you can't answer me, that's okay.
I understand that you made for Angular.**

**Comment by kukhariev** [comment]
the file is hashed twice before and after download. And the hash is not checked on the server.  I don't think that's very good.

It's possible to do that:
   ```ts
  async sendFileContent(): Promise<number | undefined> {
    const { end, body } = this.getChunk();
    const chunkHash = await this.hasher.hash(body);
    const headers = {
      'Content-Type': 'application/octet-stream',
      'Content-Range': `bytes ${this.offset}-${end - 1}/${this.size}`,
      'Chunk-md5': chunkHash
    };
    await this.request({ method: 'PUT', body, headers });
    return this.getOffsetFromResponse();
  }
```

**Comment by narutomxc** [comment]
Thank you very much,
I can now make my program upload chuck files and merge files.
