### ISSUE TITLE
Bug with 'upload' action in control method

### ISSUE THREAD

**Issue by wil92** [kukhariev/ngx-uploadx#18]

**Comment by kukhariev** [comment]
more detailed:

if concurrency=2
third call to this action does not set the event.itemOptions

```ts
        if (this.concurrency - this.runningProcess() > 0) {
          upload.upload(event.itemOptions);
        } else if (upload.status === ('added' as UploadStatus)) {
          upload.status = 'queue' as UploadStatus;
        }
```

**Comment by wil92** [comment]
I think that should be the behavior, if there are currently 2 uploading files and you put a 3rt one, this should wait for start uploading and not start immediately, because the concurrency is 2 and should not be more than 2 uploading at the same time.

For start the pending copies, I subscribe to subj observable and after some uploading finish, and the autoplay is true, then start the pending uploadings

```ts
constructor() {
    this.subj.subscribe((uploadState: UploadState) => {
      if (
        uploadState.status === 'complete' ||
        uploadState.status === 'cancelled' ||
        uploadState.status === 'error'
      ) {
        this.autoUploadFiles();
      }
    });
  }
```
So, when one of the first two copies finish, then the 3th one start uploading

**Comment by kukhariev** [comment]
to see this bug, in the file selection dialog, select 3 files with the Ctrl key pressed.
third file requests will lose the 'Content-Disposition' header.

**Comment by wil92** [comment]
I tried to reproduce the bug but i couldn't. This is a picture of one of the times I tried.
![image](https://user-images.githubusercontent.com/10768089/53532162-df3f1d80-3ac3-11e9-9d83-8f8608b830fd.png)

**Comment by kukhariev** [comment]
Chome.
http://localhost:4200/service-way, http://localhost:4200/service-code-way  
master branch, with concurrency fix  https://github.com/kukhariev/ngx-uploadx/commit/0f41f5edd47d3aa857492c198b99774ea7a62c82 (#11)
