### ISSUE TITLE
UploadxService alongside alternate File Input

### ISSUE THREAD

**Issue by Spiral1401** [kukhariev/ngx-uploadx#2]
I'm attempting to use your module (the service specifically) alongside the PrimeNG fileupload component ( https://www.primefaces.org/primeng/#/fileupload ) to give me chunking functionality. It appears to send the initial request to the configured url ( UploadxOptions.url ), but the following PUT requests that happen here:

```
Uploader.prototype.sendFile = function (start) {
...
xhr.open('PUT', this.url, true);
...
}
```

have this.url as null. Also tried setting the url in the control methods "itemOptions" parameter, but no luck there. 

I'm not sure if this is a bug, or perhaps that am I using the service in a way you didn't intend. Is the intent that the initial POST call and the subsequent PUT calls hit the same apiUrl/method?

**Comment by kukhariev** [comment]
Looks like server side doesn't return a URI in the 'Location' header.
```ts
//uploader.ts
 ...
        // get secure upload link
        this.url = xhr.getResponseHeader('Location');
```
the server has a public API?

**Comment by Spiral1401** [comment]
It isn't public - but that was exactly it. Didn't realize I needed that - I should have looked closer at your server demo. Thanks!

Another question (I can split this off into a separate issue if you like) - Is there any built in way to utilize the values returned by the initial POST response to pass back with the following PUT requests? (say the POST returns an Id, which is sent back with the PUT's). It appears the service subscription doesn't get an UploadState with the response of the POST request. I think I can probably make it work either way though, and just do the bit that creates the ID in question in the first PUT request. I will continue poking at it tomorrow. Thanks again for your help.

**Comment by Spiral1401** [comment]
Alright, I understand now that the idea is to return my ID in question as a parameter in the location header URI send back in the POST response. I've got it working now within the PrimeNG file upload component. You don't have much activity in here but just wanted to express my appreciation for putting your work out there. Thanks!

**Comment by kukhariev** [comment]
I add URI to UploadState. Thanks for pointing out the bug!
