### ISSUE TITLE
Compatibility issue with angular 5.2.0

### ISSUE THREAD

**Issue by chirag-sa** [kukhariev/ngx-uploadx#23]
Hello, 
i have installed ngx-uploadx in my angular project, but after installing it, my app stopped working.
After searching the internet i found that this plugin might have issue with my angular version.

in package.json
`
"@angular/core": "5.2.0",
"ngx-uploadx": "^2.4.5",`

if to run app with this plugin, if i need to downgrade ngx-uploadx plugin please provide me version number with that i can use this plugin in my angular 5 project

Errors coming on ng serve pasting here: 

![screen shot 2019-03-08 at 4 12 33 pm](https://user-images.githubusercontent.com/40169580/54024196-0e891500-41bd-11e9-98d7-8ce04448e0cc.png)
![screen shot 2019-03-08 at 4 14 26 pm](https://user-images.githubusercontent.com/40169580/54024274-51e38380-41bd-11e9-81f8-7b77d7089f11.png)

**Comment by kukhariev** [comment]
Hi,
ngx-uploadx v2.x.x  is to be used with Angular 6+ and rxjs 6+. For Angular v5+, use ngx-uploadx  v1.x.x

`npm install ngx-uploadx@1`

**Comment by chirag-sa** [comment]
Thanks, that worked.

Will I get all necessary features of this plugin, in ngx-uploadx@1 version.

Like Pause,Resume,Cancel, Api call on pause,resume,etc ??

**Comment by chirag-sa** [comment]
After degrading version its works, 
as i have already opened this issue after implementing i got one problem

that in params of **URL?uploadType=uploadx** in request params size is not going.

expected params
`{"name":"Fianl-It-ki-kahani.mov","mimeType":"video/quicktime","size":301351607}`
current params
`{"name":"Fianl-It-ki-kahani.mov","mimeType":"video/quicktime"}`

can you please tell, where i have gone wrong

**Comment by kukhariev** [comment]
v1.x  does not put size in the request payload  by default.
Look at [this example](https://github.com/kukhariev/ngx-uploadx/blob/v1.2.3/src/app/service-way/service-way.component.ts) how to add size.
```ts
            metadata: {
              size: item.file.size,
              lastModified: item.file.lastModified
            }
```

**Comment by kukhariev** [comment]
updated  v1.2.4 on npm  fixes this.

**Comment by chirag-sa** [comment]
Thank you @kukhariev for ultra-fast support
