### ISSUE TITLE
Please include a Changelog

### ISSUE THREAD

**Issue by siovene** [kukhariev/ngx-uploadx#271]
It's very useful for libraries like this one to include a changelog that helps with migration. I was just upgrading from 3.4 to 3.5 and that has breaking changes that are not documented.

**Describe the solution you'd like**
A Changelog file with a description of the updates and the breaking changes.

**Describe alternatives you've considered**
I have to read the code to understand how to migrate my code.

**Additional context**
Thanks!

**Comment by kukhariev** [comment]
Sorry for my mistake.
I published a new version on [npm](https://www.npmjs.com/package/ngx-uploadx/v/3.5.2) instead of the invalid 3.5.1(#247)

**Comment by siovene** [comment]
Thanks, I simply cast the response to `string` to fix the breakage, but the request for a Changelog still stands :) File uploading is the most important feature of my app (image hosting) so I have to be careful when upgrading ngx-uploadx!

**Comment by siovene** [comment]
OPh and PS: any reason why the release of 3.5.2 is not on master?

**Comment by kukhariev** [comment]
I use master branch for development. Too many major changes since version 3.5.

I have added a [changelog for 3.x](https://github.com/kukhariev/ngx-uploadx/blob/3.x/CHANGELOG.md), but I am not sure about its format.

**Comment by siovene** [comment]
Looks good to me, thanks!
