### ISSUE TITLE
Location Error

### ISSUE THREAD

**Issue by cormac01** [kukhariev/ngx-uploadx#292]
![image](https://user-images.githubusercontent.com/22728730/104004572-c7468380-519b-11eb-863c-f0748654c841.png)

Hi, 

Hoping you could help me with the above issue in snip. Have been able to send initial request to my net core api but on return to angular client, the error in image above is thrown. Have tried adding a "Location" and "Content-Location" header but with no luck. Currently, because of error, request is retried which makes sense. Have you any documentation or information on what this error relates to and what kind of response is expected back from my backend.

Also, was wondering if there is a way for my angular client to pass the chunk index to my backend. ie file has 4 chunks so with each chunk, pass param or header value with chunk index 1 - 4. Apologies for raising this as issue. This is a support query and I couldn't find any decent threads on stackoverflow.

**Comment by kukhariev** [comment]
Backend must set the `Location` header:
[uploadx api](https://github.com/kukhariev/node-uploadx/blob/master/proto.md),
[google drive api](https://developers.google.com/drive/api/v3/manage-uploads#send_the_initial_request)

If there are difficulties in implementing this apis you can use ready-made solutions such as [tusdotnet](https://github.com/tusdotnet/tusdotnet).



 Chunk index custom uploaderClass example:

```ts
// uploaderXwithChunkIndex.ts

import UploaderX from 'ngx-uploadx';

export class UploaderXwithChunkIndex extends UploaderX {
  chunkIndex = 1; // init

  async sendFileContent(): Promise<number | undefined> {
    const { end, body } = this.getChunk();
    const headers = {
      'Content-Type': 'application/octet-stream',
      'Content-Range': `bytes ${this.offset}-${end - 1}/${this.size}`,
      'Chunk-Index': this.chunkIndex
    };
    await this.request({ method: 'PUT', body, headers });
    
    this.chunkIndex++; // increase on success

    return this.getOffsetFromResponse();
  }
}
```

add to options:
```ts
  options: UploadxOptions = {
    endpoint: `${environment.api}/files`,
    ...
    chunkSize: 10 000 000,
    uploaderClass: UploaderXwithChunkIndex
  };
```

**Comment by cormac01** [comment]
Thanks for the above. This was helpful documentation. Have fixed backend and am returning Location as suggested but am still receiving error. See below execution plan and response.

1. upload request sent to "https://localhost:44357/api/Uploads/Uploads". This works fine and hits controller.
2. In by backend I have Location header set for PUT endpoint like so: `HttpContext.Response.Headers.Add(
                    "Location", $"https://localhost:44357/api/Upload/SendChunk?uploadId={uploadId}");`
3. In my client I can see the response headers which contains Location, see below: 
![image](https://user-images.githubusercontent.com/22728730/104091394-11e7fe80-5275-11eb-9547-c940c562afd9.png)
4. Unfortunately, I am still getting initial error mentioned like so:
![image](https://user-images.githubusercontent.com/22728730/104091415-36dc7180-5275-11eb-97a5-a51c75756694.png)

Can you see anything immediately obvious - bad url or http protocol must be HTTP. Thanks for any assistance.

**Comment by cormac01** [comment]
@kukhariev found the issue, issue with cors policy in my backend and needed the below header. thanks for the help.

![image](https://user-images.githubusercontent.com/22728730/104092884-c0447180-527e-11eb-974e-7cfacb11d247.png)

**Comment by kukhariev** [comment]
Yeah, I saw that, and we also need to remember to add `Range` to the `Access-Control-Allow-Headers` header for PUT requests. 
Or `context.HttpContext.Response.Headers.Add("Access-Control-Allow-Headers", "*")` , 
or take it from the browser `access-control-request-headers`

**Comment by cormac01** [comment]
cheers @kukhariev
