### ISSUE TITLE
Infinite retries upon 500 response

### ISSUE THREAD

**Issue by kontrollanten** [kukhariev/ngx-uploadx#297]
**Describe the bug**
When the server returns 500 upon file upload (PUT request) there's infinite retries.

**To Reproduce**
```
    this.uploadService.handleFiles(file, {
      endpoint: `${environment.apiUrl}/api/v1/videos/upload?uploadType=multipart`,
      multiple: false,
      token: this.authService.getAccessToken(),
    })

```

And then return 500 when the last part has been uploaded.

**Expected behavior**
**Setup details:**

- Used `ngx-uploadx`: 4.0.2
- Used Angular version: 11.1.1
- Used browser and OS: Linux, Brave
- Used server software: Express 4.12.4

**Additional context**
When I'm debugging the code it looks like line 136 is reached before the server responded with 500.

https://github.com/kukhariev/ngx-uploadx/blob/8213d9fe6cf4b59a35297721871b85c6deea5501/src/uploadx/lib/uploader.ts#L131-L136

**Comment by kukhariev** [comment]
I tried this code:
- express 4.17.1:
```ts
const options = new DiskStorage({
  directory: 'upload'
});
app.use('/upload/files', uploadx.upload(options), (req, res) => {
  res.sendStatus(500);
});
```
- modified app/service-code-way/service-code-way.component.ts, angular 11.2.7 ,  `build --prod`:
```ts
@Component({
  selector: 'app-service-way',
  templateUrl: './service-code-way.component.html'
})
export class ServiceCodeWayComponent implements OnDestroy, OnInit {
  state$!: Observable<UploadState>;
  uploads: Ufile[] = [];
  numberOfCopies = 0;
  @ViewChild('file', { read: ElementRef })
  fileInput!: ElementRef;

  private unsubscribe$ = new Subject();

  constructor(private uploadService: UploadxService) {}
  onChange(): void {
    const files = this.fileInput.nativeElement.files;
    for (let i = 0; i < files.length; i++) {
      this.uploadService.handleFiles(files[i], {
        endpoint: `${environment.api}/upload/files`,
        multiple: false,
        token: 'token'
      });
    }
  }

  ngOnInit(): void {
    this.state$ = this.uploadService.init();
    this.state$.pipe(takeUntil(this.unsubscribe$)).subscribe(state => {
      const file = this.uploads.find(item => item.uploadId === state.uploadId);
      file ? file.update(state) : this.uploads.push(new Ufile(state));
    });
  }
...
```
Couldn't catch the error.
8 retry attempts or 5 retries if i set  `retryConfig: { maxAttempts: 5 }`

sendFileContent() and getOffset() should always cause an error at code 500.

Only In `uploader-examples\multipart-form-data.ts`  a similar error is possible.

**Comment by kontrollanten** [comment]
Sorry, I wasn't clear enough. The issue appears when a 500 is returned when the file upload is completed.

**Comment by kukhariev** [comment]
I don't get endless attempts.
![2021-04-16_21-01-56](https://user-images.githubusercontent.com/13515406/115065829-554aac80-9ef7-11eb-99ec-c933ad0454d4.png)


Is it possible to test with this server code (with correct PATH and PORT)?
```js
const express = require('express');
const { uploadx } = require('node-uploadx');
//
const PATH = '/api/v1/videos/upload';
const PORT = 3003;
//
const app = express();
let retries = 0;
app.use(PATH, uploadx.upload({ directory: 'upload' }), (req, res) => {
  return res.status(500).json({ message: `is something wrong, ${retries++}` });
});

app.listen(PORT, () => console.log('listening on port:', PORT));
```

**Comment by Chocobozzz** [comment]
I cannot reproduce either, but it would be convenient to have a `shouldRetry` function in https://github.com/kukhariev/ngx-uploadx/blob/master/src/uploadx/lib/retry-handler.ts#L53 because in our use case an error 500 is considered as fatal.
