### ISSUE TITLE
Feature request: maxChunkSize

### ISSUE THREAD

**Issue by siovene** [kukhariev/ngx-uploadx#304]
**Is your feature request related to a problem? Please describe.**
An automated `chunkSize`, under excellent network conditions, can lead to a chunk being larger than what the backend allows for security reasons and memory constraints.

**Describe the solution you'd like**
I would like a `maxChunkSize` option, so that `chunkSize` can be automatic but never exceed `maxChunkSize`.

**Describe alternatives you've considered**
I have been using a fixed `chunkSize` but that's not optimal.

Thanks for considering!

**Comment by kukhariev** [comment]
Now it works like this:
```ts
import { DynamicChunk, UploadxOptions } from 'ngx-uploadx';

 DynamicChunk.maxSize = 20000000;

@Component({
...
```
I will create PR to move this to UploadxOptions.

**Comment by siovene** [comment]
@kukhariev thanks for implementing this, works as expected! <3
