### ISSUE TITLE
Chunk timeout

### ISSUE THREAD

**Issue by siovene** [kukhariev/ngx-uploadx#310]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to specify a certain timeout for a chunk, after which it should be retried.

**Describe the solution you'd like**
A `chunkTimeout` option, in seconds. If a PATCH request doesn't get a response from the server in that time, the chunk should be retried.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Thanks!

**Comment by kukhariev** [comment]
Hi  @siovene , what if I add a timeout to all requests?  https://github.com/kukhariev/ngx-uploadx/blob/1c2b3a60f1c1b968261850721178f4ca3657927e/src/app/tus/tus.component.ts#L29

**Comment by siovene** [comment]
Hi @kukhariev, maybe `retryConfig` is what I need. Could you please add documentation about what it does exactly, to the README file? (PS: `maxChunkSize` should probably be documented in README next to `chunkSize`).
Thanks!

**Comment by kukhariev** [comment]
Hi @siovene,
https://github.com/kukhariev/ngx-uploadx/blob/f95306584a48112f2272f31db37bf6c7700971d3/src/uploadx/lib/uploader.ts#L158-L159
After a timeout error a full chunk will be sent again. Is that okay?

**Comment by siovene** [comment]
Hi @kukhariev, yes, I would say that it's inline with the expectation: by default, a timeout is treated as a "retry" error. Then the flow will continue according to retryConfig (e.g. max attempts).
