### ISSUE TITLE
Big files upload error with iOS

### ISSUE THREAD

**Issue by kukhariev** [kukhariev/ngx-uploadx#316]
https://github.com/Chocobozzz/PeerTube/issues/4382
There is a issue with File API on these devices. The file stops being read after 60 seconds.

https://github.com/kukhariev/ngx-uploadx/blob/48e3756a70ddbb4a4f02195b89d7931db3049bf1/src/uploadx/lib/uploader.ts#L256-L263

**Comment by Chocobozzz** [comment]
Thanks, I spent some hours yesterday on this issue but I don't really know how to fix this. iOS bug?

**Comment by kukhariev** [comment]
@Chocobozzz  yes, https://bugs.webkit.org/show_bug.cgi?id=228683

**Comment by kukhariev** [comment]
Although this error no longer appears on iOS versions 15.3 and above, there are still many devices running iOS 14 and older?
