### ISSUE TITLE
dynamic directive id

### ISSUE THREAD

**Issue by ingen2** [kukhariev/ngx-uploadx#320]
Hi
I need many multiple uploader , per my categories.

How can I set directives id dynamically

I used upload directive in *ngFor , but directives id confilicted:

my Code :

     <div *ngFor="let item of categories">
        <h3>{{item.name}}</h3>
        <input
        [attr.id]="item.id"
        (click)="???????????.value = ''"   // <== My problem is here 
        (state)="onStateChanged($event)"
        [control]="control"
        [uploadx]="tusoptions"
        id="{{item.id}}"
        type="file"
        class="file_select"
        />
    </div>

What to write in ???????? place?

**Comment by kukhariev** [comment]
Hello,
https://angular.io/guide/template-reference-variables#template-input-variable
Template reference variables not work in *ngFor.

https://github.com/kukhariev/ngx-uploadx/issues/13 what is `(click)` is doing. It's not usually needed.
I suggest wrapping the directive in a component:

```html
<div *ngFor="let item of categories">
  <upload-input-wrapper [item]="item"></upload-input-wrapper>
</div>
```
