### ISSUE TITLE
why not use real filename for completed uploading

### ISSUE THREAD

**Issue by ajeecai** [kukhariev/ngx-uploadx#352]
upload via tus may generate two files: one is a meta file containing original filename, size, etc, another is the uploaded file but with hash value as its name. 

My question is why not turn it into real file name,  although we could run a background process to do it according to meta file.

Thanks

**Comment by kukhariev** [comment]
Maybe I didn't understand the question very well.

Here are some options:
```ts
tus.on('completed' , renameToOriginal);
```
 ```ts
const opts: DiskStorageOptions = {
  maxUploadSize: '5GB',
  directory: 'upload',
  onComplete: renameToOriginal
};
const tus = new Tus(opts);
```
or [express example](https://github.com/kukhariev/node-uploadx/blob/master/examples/express-tus.ts)

**Comment by ajeecai** [comment]
Hi @kukhariev, that is what I mean. Great help from you, thanks.
