### ISSUE TITLE
custom metadata is not working well

### ISSUE THREAD

**Issue by ajeecai** [kukhariev/ngx-uploadx#354]
The code looks like this:
![image](https://user-images.githubusercontent.com/3023271/143687879-d5d18cb7-6967-4aa3-a4e7-8b06f3ac620a.png)

When uploading completed, the onComplete callback in server prints:
![image](https://user-images.githubusercontent.com/3023271/143687932-1e2910e0-0ecd-40e6-b629-70a953789f54.png)

But in some cases, I can see them： 
```
  metadata: [Object: null prototype] {
    ...
   curPath: xxx
   userId: yyy
  },
```

Is anything wrong?

Thanks

**Comment by kukhariev** [comment]
Hi!
 You can see in the first POST request `Upload-Metadata` header what metadata the client sends (b64 encoded).
Are there `curPath` and `userId` fields?

**Comment by ajeecai** [comment]
Hi @kukhariev , I may find out the reason. In some cases I pass curPath with a null string (stands for root dir), then this looks like unacceptable and lead to userId not being included although userId is not null. Now I pass curPath as '.' then all works well. If it is regarded as not an issue, please close it.

Thanks
