### ISSUE TITLE
How to confirm before uploading via drop and drop

### ISSUE THREAD

**Issue by ajeecai** [kukhariev/ngx-uploadx#360]
Hi,

Suppose the existing files could be known in frontend, just want to pop a confirmation dialog before any real uploading happens. 

But uploading via drop and drop, it looks like there is no place to intercept and wait for the user confirmation. 

Appreciate your idea.

Thanks

**Comment by kukhariev** [comment]
Add to options `autoUpload: false`,
the "added" event will be emitted when the file is dropped.

**Comment by ajeecai** [comment]
Thank you, with this option and the instruction mentioned, it works.
