### ISSUE TITLE
How to append additional params to the request (service)?

### ISSUE THREAD

**Issue by zr87** [kukhariev/ngx-uploadx#387]
I'm using the service-code-way example with the MultiPartFormData class as ulploaderClass given in the options config.

Scenario: the user can select between 3 options  before the files are added.  I'd like to append additional params to the file upload request.  

A hacky solution what popped into my mind is using a interceptor to modify the outgoing request.
It could work if the lib uses HttpClient - I guess.

**Comment by kukhariev** [comment]
Hello,
Can you please specify what you call `additional params`?
query URL parameters?
