### ISSUE TITLE
throw error on using ngx-uploadx and uploadx-server with s3 

### ISSUE THREAD

**Issue by Aviico2** [kukhariev/ngx-uploadx#405]
I use Ngx-uploadx in the front-end and in the back-end I use uploadx server with s3. 

**Frontend Code:**
  state$: Observable<UploadState>;
  uploads$: Observable<Uploader[]>;
  options: UploadxOptions = {
    endpoint: 'http://localhost:4000/uploads'
  };

  constructor(private uploadService: UploadxService) {
    this.uploads$ = this.uploadService.connect(this.options);
    this.state$ = this.uploadService.events;
  }

  pause(): void {
    this.uploadService.control({ action: 'pause' });
  }

  upload(): void {
    this.uploadService.control({ action: 'upload' });
  }

**Backend Code:**

const storage = new S3Storage({
    endpoint: '',
    bucket: '',
    region: '',
    apiVersion: '2006-03-01',
    credentials: {
        accessKeyId: '',
        secretAccessKey: '',
    },
    forcePathStyle: true,
    expiration: { maxAge: '1h', purgeInterval: '15min' },
    onComplete: file => console.log('File upload complete: ', file)
});

app.use('/uploads', uploadx({ storage }), function (req, res) {
    var file = req.body;
    console.log('File upload complete: ', file.originalName);
    return res.json(file);
});

At the end of the upload file, it throws this error.

**Error:**
{
  "file": {},
  "name": "file.mp4",
  "progress": 96.87,
  "remaining": 0,
  "response": {
    **"error": {
      "message": "Your proposed upload is smaller than the minimum allowed size",
      "code": "EntityTooSmall",
      "name": "EntityTooSmall"
    }**
  },
  "responseHeaders": {
    "cache-control": "no-store",
    "content-length": "133",
    "content-type": "application/json"
  },
  "responseStatus": 400,
  "size": 42739882,
  "speed": 36402001,
  "status": "error",
  "uploadId": "5579b551944f8fe1",
  "url": "http://localhost:4000/uploads?upload_id=97e30059e4586102-f19bfa7526c31afa-2ef9b71128d092cc"
}

**Comment by kukhariev** [comment]
Hello, 
for s3 you must specify a fixed chunk size greater than 5MB. i.e. 
```ts
options: UploadxOptions = {
  endpoint: 'http://localhost:4000/uploads',
  chunkSize: 10*1024*1024 // 10MB
}
```
