### ISSUE TITLE
missing Metadata member

### ISSUE THREAD

**Issue by gerardorosiles** [kukhariev/ngx-uploadx#444]
Hi, 

I am working with a very old code base (5-6 years old that  has the following version range specified in the package.json file:
"ngx-uploadx": "^3.3.5",

When building the code I am getting this error:

```
ERROR in src/app/upload/model/tus-ext.ts:28:14 - error TS2305: Module '"../../../../node_modules/ngx-uploadx/ngx-uploadx"' has no exported member 'Metadata'.

28 import {b64, Metadata, resolveUrl, Tus, UploadxOptions} from 'ngx-uploadx';
```

I tried a couple of older versions and even a newer versions with no success.

Can you provide some pointers on a version where the Metadata object is/was available? Or maybe it was not officially supported?

Thanks

**Comment by kukhariev** [comment]
Hi,

from version 4.0.0 and possibly also in 3.5.1

**Comment by gerardorosiles** [comment]
Thanks very much for your help! Version 3.5.1 worked.

npm was installing 3.5.2 so it just skipped the proper version.
