### ISSUE TITLE
Unable to build the angular application due to **uploadx**

### ISSUE THREAD

**Issue by akshaybogar1984** [kukhariev/ngx-uploadx#452]
**Description:**
Unable to build the angular application due to **uploadx**

**Steps to reproduce:**
1. execute npm i ngx-uploadx in our sample angular application
2. build is failing after build. 

@Component({
  selector: 'app-home',
  templateUrl: `
  <input type="file" [**uploadx**]="options" (state)="onUpload($event)">
  `
})

**Comment by kukhariev** [comment]
Yes, that's a typo. Thank you very much!

```ts
@Component({
  selector: 'app-home',
  template: `
  <input type="file" [uploadx]="options" (state)="onUpload($event)">
  `
})
```
