### ISSUE TITLE
getOffsetFromResponse isn't behaving quite right

### ISSUE THREAD

**Issue by JohnHayford** [kukhariev/ngx-uploadx#46]
in uploaderx.ts, getOffsetFromResponse  doesn't seem to be behaving quite right for the following use cases.
Missing Range: this should be allowed, using the same Google Doc upload reference (https://developers.google.com/drive/api/v3/manage-uploads#resume-upload)  that you are using.  This should tell the service that no content has been received and to start at byte 0.

"Range: bytes=0-1" : This will get matched as "-1" and will send from byte 0.  There's not really a standard on using the Range header on a response, so not sure of what the right answer is.  Possible solution would be looking for two dashes when matching "-1", ie, "-1--1" for no content. /(--1|\d+)$/g
Also looking for just "-1", like "Range: bytes=-1" could work.

https://github.com/kukhariev/ngx-uploadx/blob/master/src/uploadx/src/uploaderx.ts

**Comment by kukhariev** [comment]
I think it'll work 🛴
https://github.com/kukhariev/ngx-uploadx/blob/484729da48e4ab1225b1f029974fc776a35f50e7/src/uploadx/src/uploaderx.spec.ts#L27-L43
