### ISSUE TITLE
Endpoint protocol automatically changed by the code from `https` to `http` when origin is `http`

### ISSUE THREAD

**Issue by dorontal** [kukhariev/ngx-uploadx#59]
Apologies if the following isn't 100% clear. I can clarify further. But in a nutshell the main question is: why does the code change the endpoint from `https://...` to `http://...` when the origin is `http` and is that a bug?

---- Thanks very much for a great piece of software regardless!

In this entire discussion, I am using `UploadxService.handleFile()` - that's where the URL of the endpoint specified in the options object given to it gets automatically converted from `https` to `http` (only when running from an `http` origin).

When developing / testing the code, I serve my single page app on a local machine server and go to url `http://localhost:8100` to test a running of the app.

That app connects to an Uploadx node server that sits behind `https` protocol, and runs on a URL like:

    https://upload.example.com

When the app is served from an `https` origin, e.g. `https://app.example.com` - then everything works as expected - the app can access the Uploadx node server with no problem, all works.

But when I develop / test the code and serve the app locally, the origin has protocol `http`, not `https`. In that case, for some reason, when using `handleFile` of the service version of Uploadx (`UploadxService`), it changes the protocol when making the request, even though the endpoint I specify in options given to handle file is preceded by `https`. I give `handle file()` the option `endopoint: https://upload.example.com/upload` but it actually changes that endpoint and makes the request at a different URL, changing the protocol from `https` to `http`, i.e. it goes to endpoint `http://upload.example.com/upload` instead, because the origin had `http` in it.

This causes a problem, I need to access the `https:` endpoint always, not the `http` but it gets converted automatically in the code. Is there a way to stop it from converting from `https` to `http` when the origin is `http`?

**Update**
I am noticing in the logs of the server side (Uploadx node server) that the endpoint actually seems to have the protocol stripped when it arrives - here's a line from the Uploadx server log: 

```
<ip#>  - - [20/Sep/2019:21:49:15 +0000] "OPTIONS /upload?uploadType=uploadx&upload_id=52014dbf3fbda4e3cef2f4ec3c0f2c53 ...
```

So it's not that `https` gets converted to `http` but it gets stripped, then `http` is assumed because of the origin's `http` that it comes from.  It's possible I am not understanding something here, but perhaps if we kept the `https://` and did not strip it from the endpoint URL, that would solve the problem?

More specifically, looking at the Network tab of the developer tools in chrome when running the app from origin `http://localhost:8100`, and uploading one file via handleFile, I see the following sequence of requests (using `example.com` instead of my actual server):
```
https://upload.example.com/upload?uploadType=uploadx (status 204)
https://upload.example.com/upload?uploadType=uploadx (status 201)
http://upload.example.com/upload?uploadType=uploadx&upload_id=... (status 301)
http://upload.example.com/upload?uploadType=uploadx&upload_id=... (status 301)
http://upload.example.com/upload?uploadType=uploadx&upload_id=... (status 301)
http://upload.example.com/upload?uploadType=uploadx&upload_id=... (status 301)
http://upload.example.com/upload?uploadType=uploadx&upload_id=... (status 301)
...
```

i.e. as soon as we see an &upload_id in the URL, it becomes `http` while it should be `https` to work for my use case.

**How to replicate**
1) Set up an Uploadx node server behind `https`
2) Run an app in your browser, locally served from `http://localhost*` that uploads a file to the server above via `UploadxServer.handleFile()` - the upload will fail as described above.

**Comment by kukhariev** [comment]
Thank you for reporting this, it'll be fixed.
As a workaround you might want to add  `useRelativeLocation: true`  to server config

**Comment by kukhariev** [comment]
Version 3.2.2 must now work correctly with mixed protocols.

**Comment by dorontal** [comment]
Thanks so much!  I am extremely grateful for this fix. It saves me a ton of time in the development process.
Best, -Doron



 ---- On Sat, 21 Sep 2019 17:29:07 -0400 q_h <notifications@github.com> wrote ----
