### ISSUE TITLE
Refresh token handling

### ISSUE THREAD

**Issue by vduc** [kukhariev/ngx-uploadx#6]
Hi, 

I have a question about access token. When a user is authenticated, a token is sent. On my server, the validity of this token is 5min. Every 5 min, a request to refresh the token is sent to the server.

Is it possible to update the token in the service? 
I go through the source code but I don't see anything for it. I would like to send the new token to the service and this token will be used for all following request. 

The other thing that will be useful is to retry on failed upload after an error due to an old token.

Is it possible to do something like that with your library? If yes, how?

Thanks in advance for your response

Virginie

**Comment by kukhariev** [comment]
Hi.
v 2.1.0  with 
```ts
this.uploadService.control({
   action: 'refreshToken',
    token: 'newToken'
 });
```
and more.
I hope I will update the documentation and examples later.

**Comment by vduc** [comment]
Perfect,

Thanks a lot for all you work.
