### ISSUE TITLE
pause with uploadId is pausing all the queue

### ISSUE THREAD

**Issue by w2kzzz** [kukhariev/ngx-uploadx#68]
**Describe the bug**
The pause with uploadId seems to be pausing all the queue.

**To Reproduce**
calling simply the service passing the uploadId.

`this.uploadService.control({ action: 'pause', uploadId });`

**Expected behavior**
Only the element with the uploadId should be paused.
**Setup details:**

- Used `ngx-uploadx` latest
- Used Angular version 8
- Used browser and OS, MacOS, Chrome

**Comment by kukhariev** [comment]
Hi Luis!
Could not reproduce the error.

![1](https://user-images.githubusercontent.com/13515406/68839014-dda89a80-06d0-11ea-8848-255ab7ce7fb3.gif)

Maybe the component lost `uploadId` somewhere.
The snippet which will help find exactly where:
```ts
  pause(uploadId: string) {
    if (!uploadId) {
      throw new Error(`Invalid upload id: ${uploadId}`);
    }
    this.uploadService.control({ action: 'pause', uploadId });
  }
```

**Comment by w2kzzz** [comment]
Thanks for the response, I’ll put something together and comment again since I’m trying to use it in NGXS state so that implementation and the pattern I’m taking could be the issue. It’s 4:21 am in here so I’ll do it once I arrive to the office :)

**Comment by w2kzzz** [comment]
seems that in fact i'm loosing the id, i'll check my code, thanks for the response
