### ISSUE TITLE
Any good way to rename a queue element?

### ISSUE THREAD

**Issue by w2kzzz** [kukhariev/ngx-uploadx#69]
probably this is a silly question and not the place to put it, but is there any consistent way to rename the file once is in the queue already?

i'm using NGXS to handle the uploads with an application store and i'm copying the content of the uploadService queue into my own thing, however my rename functionality gets overwritten by what it is inside the queue at the time i restart the upload.

the endpoint gets updated properly and the file sent to the server have the proper name, but visually my user will still see the old name.

hope this makes sense since this is not a bug.

i can't copy my code since is a corporate application.

but the state is just a copy of the queue.

i'm using the latest of the library.

**Comment by kukhariev** [comment]
Hi!
If you change the metadata of a file, you should also reset its `url`. Otherwise the server will ignore the changes.

```ts
  rename(id: string, newName: string) {
    const [target] = this.uploadService.queue.filter(({ uploadId }) => uploadId === id);
    target.metadata.name = newName;
    target.url = '';
  }
```
